### ISSUE TITLE
Request for comment: Opening strategies

### ISSUE THREAD

**Issue by fntlnz** [vim-php/vim-relatedtest#6]
While testing I always keep an opened right split with the implementation along with a left one for the tests.

For this purpose I'm proposing to define some kind of "opening strategies" instead of the default ":e" that now open a new buffer in the current window (https://github.com/wdalmut/vim-relatedtest/blob/master/plugin/relatedtest.vim#L27-L31)

Some possible strategies can be:

- Open in a vertical split (:vsp)
- Open in orizontal split (:sp)
- Open in tab (:tabedit)

and so on....

What do you think?

**Comment by wdalmut** [comment]
yep cool!
